// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWDbByEtPy4QFwkftqwxSh1K2Uo0JCPA0',
    appId: '1:601124488677:web:d726b34dc62568fd719b0c',
    messagingSenderId: '601124488677',
    projectId: 'gomart-43a88',
    authDomain: 'gomart-43a88.firebaseapp.com',
    storageBucket: 'gomart-43a88.firebasestorage.app',
    measurementId: 'G-MKJBXRFPPF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5rx9ZmT8pRqGoQRZCN4w6qu7s92pxUnE',
    appId: '1:601124488677:android:3ee6c238fe0a5bd9719b0c',
    messagingSenderId: '601124488677',
    projectId: 'gomart-43a88',
    storageBucket: 'gomart-43a88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0ht6g9cJ1ndUkDs9EPN-qrNzYE5G2H8c',
    appId: '1:601124488677:ios:10740a5061e4b7d4719b0c',
    messagingSenderId: '601124488677',
    projectId: 'gomart-43a88',
    storageBucket: 'gomart-43a88.firebasestorage.app',
    iosBundleId: 'com.example.gomart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0ht6g9cJ1ndUkDs9EPN-qrNzYE5G2H8c',
    appId: '1:601124488677:ios:10740a5061e4b7d4719b0c',
    messagingSenderId: '601124488677',
    projectId: 'gomart-43a88',
    storageBucket: 'gomart-43a88.firebasestorage.app',
    iosBundleId: 'com.example.gomart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWDbByEtPy4QFwkftqwxSh1K2Uo0JCPA0',
    appId: '1:601124488677:web:96d2fb18c71294e8719b0c',
    messagingSenderId: '601124488677',
    projectId: 'gomart-43a88',
    authDomain: 'gomart-43a88.firebaseapp.com',
    storageBucket: 'gomart-43a88.firebasestorage.app',
    measurementId: 'G-TKR35VRSMX',
  );
}
